"""
DiffKnock: diffusion-based model-X knockoffs.

Knockoffs are generated by noising each observed row forward to an intermediate
level t* and running a learned reverse diffusion back from there, so that each
knockoff stays coupled to its own observation.  Setting t* to None (or to the
full chain length) recovers unconditional sampling, for which the coupling
Cov(X, X_tilde) vanishes.

Feature importance is measured on a DeepLINK-style network by either a
gradient-based or a filter-based statistic, both antisymmetric, and features are
selected by the knockoff+ threshold.

Typical use:

    dk = DiffKnock(input_dim=p)
    dk.train_diffusion_for_knockoffs(X, n_epochs=600)
    Xt = dk.generate_knockoffs(X, t_star=400)
    # ... fit a DeepLINK model on (X, Xt, y), then
    W  = dk.compute_deeplink_statistics(model)
    S  = dk.select_features(W, fdr_threshold=0.2)

or end to end via DiffusionXKnockoff(input_dim=p).run(X, y, t_star=400).
"""

import os

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

# Default tie level used by the end-to-end pipeline when none is supplied.
# Smaller values keep the knockoff closer to its own row; None gives
# unconditional sampling, for which Cov(X, X_tilde) = 0.
DEFAULT_T_STAR = 500

def _cross_cov_stats(X, Xt):
    """Mean |diagonal| and mean |off-diagonal| of the empirical Cov(X, X_tilde) block."""
    X = np.asarray(X); Xt = np.asarray(Xt)
    Xc = X - X.mean(axis=0, keepdims=True)
    Tc = Xt - Xt.mean(axis=0, keepdims=True)
    C = (Xc.T @ Tc) / max(X.shape[0] - 1, 1)
    diag = float(np.abs(np.diag(C)).mean())
    n_off = max(C.size - C.shape[0], 1)
    off = float((np.abs(C).sum() - np.abs(np.diag(C)).sum()) / n_off)
    return diag, off


# Accumulates (scenario, amplitude, generator, mean|cov_jj|, mean|cov_jk|)
_XCOV_LOG = []


# ============= DeepLINK Components =============

class DeepLINK(nn.Module):
    """DeepLINK architecture for feature selection with knockoffs - optimized for TPM"""
    def __init__(self, input_dim, hidden_dims=[100, 50], output_dim=1, dropout=0.1):
        super().__init__()
        self.input_dim = input_dim
        
        # Pairwise filter layer - properly initialized
        self.filter_weights = nn.Parameter(torch.ones(input_dim, 2) * 0.5)
        
        # MLP layers with LayerNorm for TPM data
        layers = []
        prev_dim = input_dim
        for hidden_dim in hidden_dims:
            layers.extend([
                nn.Linear(prev_dim, hidden_dim),
                nn.LayerNorm(hidden_dim),  # Add LayerNorm for TPM data
                nn.ReLU(),
                nn.Dropout(dropout)
            ])
            prev_dim = hidden_dim
        
        layers.append(nn.Linear(prev_dim, output_dim))
        self.mlp = nn.Sequential(*layers)
        
    def forward(self, x, x_tilde):
        """Forward pass with original features x and knockoffs x_tilde"""
        # Get filter weights
        z = self.filter_weights[:, 0]
        z_tilde = self.filter_weights[:, 1]
        
        # Normalize filters to sum to 1 (antisymmetric constraint)
        norm = torch.abs(z) + torch.abs(z_tilde) + 1e-8
        z = z / norm
        z_tilde = z_tilde / norm
        
        # Compute filtered features
        filtered_features = x * z.unsqueeze(0) + x_tilde * z_tilde.unsqueeze(0)
        
        # Pass through MLP
        output = self.mlp(filtered_features)
        
        return output
    
    def get_filter_weights(self):
        """Get the normalized filter weights for knockoff statistics"""
        z = self.filter_weights[:, 0]
        z_tilde = self.filter_weights[:, 1]
        
        # Normalize
        norm = torch.abs(z) + torch.abs(z_tilde) + 1e-8
        z = z / norm
        z_tilde = z_tilde / norm
        
        return z, z_tilde

# ============= Diffusion based Knockoff =============
class DiffKnock:
    """Diffusion-based Knockoff Generation for TPM data"""
    def __init__(self, input_dim, device='cuda' if torch.cuda.is_available() else 'cpu'):
        self.input_dim = input_dim
        self.device = device
        self.diffusion = None
        self.deepLINK = None
        self.scaler = None
        
        
    def train_diffusion_for_knockoffs(self, X_data, n_epochs=500, batch_size=64, lr=1e-4):
        """Train diffusion model to learn the data distribution"""
        print("Training diffusion model for knockoff generation...")
        
        # Prepare data
        X_tensor = torch.FloatTensor(X_data).unsqueeze(1)  # Add sequence dimension
        dataset = TensorDataset(X_tensor)
        dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, 
                              pin_memory=torch.cuda.is_available())
        
        # Initialize diffusion model
        model = DiffusionTransformer(
            input_dim=self.input_dim,
            hidden_dim=256,
            depth=6,
            heads=8,
            dim_head=32,
            dropout=0.1
        )
        
        self.diffusion = ImprovedDDPM(model, num_timesteps=1000, device=self.device)
        
        # Optimizer
        optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=n_epochs)
        
        # Training loop
        losses = []
        model.train()
        
        for epoch in range(n_epochs):
            epoch_loss = 0
            for batch_idx, (batch,) in enumerate(dataloader):
                batch = batch.to(self.device)
                batch_size_actual = batch.shape[0]
                
                # Sample random timesteps
                t = torch.randint(0, self.diffusion.num_timesteps, 
                                 (batch_size_actual,), device=self.device).long()
                
                # Compute loss
                loss = self.diffusion.p_losses(batch, t)
                
                # Backward pass
                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                
                epoch_loss += loss.item()
            
            scheduler.step()
            avg_loss = epoch_loss / len(dataloader)
            losses.append(avg_loss)
            
            if (epoch + 1) % 100 == 0:
                print(f"Epoch {epoch+1}/{n_epochs}, Loss: {avg_loss:.4f}")
        
        return losses
    
    def generate_knockoffs(self, X_data, t_star=None):
        """
        Generate diffusion knockoffs.

        t_star = None or >= num_timesteps
            ORIGINAL behaviour: unconditional sampling from pure noise.  X_tilde is
            row-independent of X, hence Cov(X, X_tilde) = 0.
        t_star = int in [1, num_timesteps)
            Row-tied sampling: X is noised to level t_star then denoised back, so
            row i of X_tilde stays tied to row i of X and Cov(X, X_tilde) != 0.
        """
        T = self.diffusion.num_timesteps
        with torch.no_grad():
            n_samples = X_data.shape[0]
            if t_star is None:
                print("Generating knockoff variables (unconditional, t*=T)...")
                X_knockoffs = self.diffusion.sample((n_samples, 1, self.input_dim))
            else:
                print(f"Generating knockoff variables (row-tied, t*={int(t_star)})...")
                x0 = torch.as_tensor(np.asarray(X_data), dtype=torch.float32,
                                     device=self.device).unsqueeze(1)
                X_knockoffs = self.diffusion.sample_tied(x0, int(t_star))
            X_knockoffs = X_knockoffs.squeeze(1).cpu().numpy()

        return X_knockoffs
    
    def compute_gradient_based_statistics(self, X, X_tilde, y, model, criterion, batch_size=100):
        """Compute gradient-based importance statistics with proper batching"""
        print("Computing gradient-based statistics...")
        
        n_samples = X.shape[0]
        n_features = X.shape[1]
        
        # Initialize gradient accumulators
        grad_X_accum = np.zeros(n_features)
        grad_X_tilde_accum = np.zeros(n_features)
        
        # Process in batches to avoid memory issues
        model.eval()
        
        for i in range(0, n_samples, batch_size):
            end_idx = min(i + batch_size, n_samples)
            
            # Get batch
            X_batch = torch.FloatTensor(X[i:end_idx]).to(self.device).requires_grad_(True)
            X_tilde_batch = torch.FloatTensor(X_tilde[i:end_idx]).to(self.device).requires_grad_(True)
            y_batch = torch.FloatTensor(y[i:end_idx]).to(self.device)
            
            # Forward pass
            output = model(X_batch, X_tilde_batch)
            loss = criterion(output.squeeze(), y_batch)
            
            # Compute gradients
            grads = torch.autograd.grad(loss, [X_batch, X_tilde_batch], create_graph=False)
            
            # Accumulate absolute gradients
            grad_X_accum += torch.abs(grads[0]).sum(dim=0).detach().cpu().numpy()
            grad_X_tilde_accum += torch.abs(grads[1]).sum(dim=0).detach().cpu().numpy()
        
        # Average gradients
        G_j = grad_X_accum / n_samples
        G_j_tilde = grad_X_tilde_accum / n_samples
        
        # Compute knockoff statistics
        W_grad = G_j - G_j_tilde
        
        return W_grad
    
    def compute_deeplink_statistics(self, model):
        """Compute filter-based statistics - ORIGINAL VERSION"""
        print("Computing filter-based statistics...")
        
        # Get filter weights
        z, z_tilde = model.get_filter_weights()
        
        # Get MLP weights to compute importance (matching original DeepLINK)
        with torch.no_grad():
            # Extract Linear layers from the MLP
            linear_layers = []
            for module in model.mlp:
                if isinstance(module, nn.Linear):
                    linear_layers.append(module)
            
            # Compute combined weight w by multiplying through the network
            # Start from output layer and work backwards
            w = linear_layers[-1].weight.data  # Shape: (1, hidden_dim_last)
            
            # Multiply through all linear layers (excluding the last one we already have)
            for layer in reversed(linear_layers[:-1]):
                w = w @ layer.weight.data  # Matrix multiplication through the network
            
            # w now has shape (1, input_dim) where input_dim = p_genes
            w = w.squeeze()  # Remove the batch dimension, shape: (p_genes,)
        
        # Compute knockoff statistics as in original paper: W = (w * z)² - (w * z_tilde)²
        w = w.cpu().numpy()
        z = z.detach().cpu().numpy()  # ADD detach() here
        z_tilde = z_tilde.detach().cpu().numpy()  # ADD detach() here
        
        W_filt = (w * z) ** 2 - (w * z_tilde) ** 2
        
        return W_filt

    
    def select_features(self, W_j, fdr_threshold=0.2):
        def knockoff_plus_threshold(W, q):
            # Get the absolute values of statistics
            abs_W = np.abs(W)
            
            # Sort in descending order
            sorted_indices = np.argsort(abs_W)[::-1]
            sorted_W = W[sorted_indices]
            sorted_abs_W = abs_W[sorted_indices]
            
            # Find threshold using the knockoff+ procedure
            threshold = np.inf
            
            # Consider all possible thresholds (including positive values)
            unique_vals = np.unique(sorted_abs_W[sorted_abs_W > 0])
            
            if len(unique_vals) == 0:
                # No non-zero statistics, can't select anything
                return np.inf
            
            # Add a small value below the minimum to consider selecting all
            thresholds_to_try = np.append(unique_vals, [0, unique_vals.min() / 2])
            thresholds_to_try = np.sort(thresholds_to_try)[::-1]  # Descending order
            
            for t in thresholds_to_try:
                # Count discoveries and false discoveries
                selected = W >= t
                n_selected = np.sum(selected)
                
                if n_selected == 0:
                    continue
                    
                # Knockoff+ estimate of false discoveries
                n_negative = np.sum(W <= -t)
                
                # FDP estimate with offset=1 for knockoff+
                fdp_estimate = (1 + n_negative) / max(n_selected, 1)
                
                # Check if this threshold achieves target FDR
                if fdp_estimate <= q:
                    threshold = t
                    break
            
            return threshold
        
        threshold = knockoff_plus_threshold(W_j, fdr_threshold)
        selected_features = np.where(W_j >= threshold)[0]
        
        return selected_features

class SinusoidalPositionEmbeddings(nn.Module):
    """Sinusoidal position embeddings for time steps"""
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, time):
        device = time.device
        half_dim = self.dim // 2
        embeddings = np.log(10000) / (half_dim - 1)
        embeddings = torch.exp(torch.arange(half_dim, device=device) * -embeddings)
        embeddings = time[:, None] * embeddings[None, :]
        embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)
        return embeddings

class ConditionalLayerNorm(nn.Module):
    """Conditional Layer Normalization with time embedding"""
    def __init__(self, dim, time_dim):
        super().__init__()
        self.norm = nn.LayerNorm(dim)
        self.scale = nn.Linear(time_dim, dim)
        self.shift = nn.Linear(time_dim, dim)
        
    def forward(self, x, t):
        normalized = self.norm(x)
        scale = self.scale(t).unsqueeze(1)
        shift = self.shift(t).unsqueeze(1)
        return normalized * (1 + scale) + shift

class TransformerBlock(nn.Module):
    """Transformer block with cross-attention and time conditioning"""
    def __init__(self, dim, heads=8, dim_head=64, mlp_dim=None, dropout=0.1, time_dim=None):
        super().__init__()
        inner_dim = dim_head * heads
        mlp_dim = mlp_dim or dim * 4
        
        self.heads = heads
        self.scale = dim_head ** -0.5
        
        # Self-attention components
        self.norm1 = ConditionalLayerNorm(dim, time_dim) if time_dim else nn.LayerNorm(dim)
        self.to_qkv = nn.Linear(dim, inner_dim * 3, bias=False)
        self.to_out = nn.Sequential(
            nn.Linear(inner_dim, dim),
            nn.Dropout(dropout)
        )
        
        # MLP components
        self.norm2 = ConditionalLayerNorm(dim, time_dim) if time_dim else nn.LayerNorm(dim)
        self.mlp = nn.Sequential(
            nn.Linear(dim, mlp_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(mlp_dim, dim),
            nn.Dropout(dropout)
        )
        
    def forward(self, x, t=None):
        # Self-attention
        if t is not None:
            h = self.norm1(x, t)
        else:
            h = self.norm1(x)
            
        qkv = self.to_qkv(h).chunk(3, dim=-1)
        q, k, v = map(lambda t: t.view(t.shape[0], t.shape[1], self.heads, -1).transpose(1, 2), qkv)
        
        dots = torch.matmul(q, k.transpose(-1, -2)) * self.scale
        attn = dots.softmax(dim=-1)
        
        out = torch.matmul(attn, v)
        out = out.transpose(1, 2).contiguous().view(out.shape[0], out.shape[2], -1)
        x = x + self.to_out(out)
        
        # MLP
        if t is not None:
            h = self.norm2(x, t)
        else:
            h = self.norm2(x)
        x = x + self.mlp(h)
        
        return x

class DiffusionTransformer(nn.Module):
    """State-of-the-art Diffusion Transformer for TPM data"""
    def __init__(self, input_dim, hidden_dim=256, depth=6, heads=8, dim_head=32, 
                 mlp_dim=None, dropout=0.1, time_dim=128):
        super().__init__()
        
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        
        # Time embeddings
        self.time_mlp = nn.Sequential(
            SinusoidalPositionEmbeddings(time_dim),
            nn.Linear(time_dim, time_dim * 4),
            nn.GELU(),
            nn.Linear(time_dim * 4, time_dim),
        )
        
        # Input projection
        self.input_proj = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.LayerNorm(hidden_dim)
        )
        
        # Positional encoding for sequence elements
        self.pos_embedding = nn.Parameter(torch.randn(1, 1000, hidden_dim))
        
        # Transformer blocks
        self.transformer_blocks = nn.ModuleList([
            TransformerBlock(hidden_dim, heads, dim_head, mlp_dim, dropout, time_dim)
            for _ in range(depth)
        ])
        
        # Output projection
        self.output_norm = nn.LayerNorm(hidden_dim)
        self.output_proj = nn.Linear(hidden_dim, input_dim)
        
    def forward(self, x, t):
        # x shape: (batch_size, seq_len, input_dim)
        # t shape: (batch_size,)
        
        batch_size, seq_len, _ = x.shape
        
        # Time embedding
        t_emb = self.time_mlp(t)
        
        # Project input
        h = self.input_proj(x)
        
        # Add positional encoding
        h = h + self.pos_embedding[:, :seq_len, :]
        
        # Pass through transformer blocks
        for block in self.transformer_blocks:
            h = block(h, t_emb)
        
        # Output projection
        h = self.output_norm(h)
        output = self.output_proj(h)
        
        return output

class ImprovedDDPM:
    """Improved Denoising Diffusion Probabilistic Model with advanced scheduling"""
    def __init__(self, model, beta_start=0.0001, beta_end=0.02, num_timesteps=1000,
                 loss_type='l2', device='cuda' if torch.cuda.is_available() else 'cpu'):
        self.model = model.to(device)
        self.num_timesteps = num_timesteps
        self.loss_type = loss_type
        self.device = device
        
        # Improved noise schedule (cosine schedule)
        self.betas = self._cosine_beta_schedule(num_timesteps, beta_start, beta_end).to(device)
        self.alphas = (1.0 - self.betas).to(device)
        self.alphas_cumprod = torch.cumprod(self.alphas, dim=0).to(device)
        self.alphas_cumprod_prev = torch.cat([torch.ones(1).to(device), self.alphas_cumprod[:-1]]).to(device)
        
        # Pre-compute values for efficiency
        self.sqrt_alphas_cumprod = torch.sqrt(self.alphas_cumprod).to(device)
        self.sqrt_one_minus_alphas_cumprod = torch.sqrt(1.0 - self.alphas_cumprod).to(device)
        self.sqrt_recip_alphas = torch.sqrt(1.0 / self.alphas).to(device)
        self.posterior_variance = (self.betas * (1.0 - self.alphas_cumprod_prev) / (1.0 - self.alphas_cumprod)).to(device)
        
    def _cosine_beta_schedule(self, timesteps, beta_start=0.0001, beta_end=0.02):
        """Cosine schedule for better sampling quality"""
        s = 0.008
        steps = timesteps + 1
        x = torch.linspace(0, timesteps, steps)
        alphas_cumprod = torch.cos(((x / timesteps) + s) / (1 + s) * torch.pi * 0.5) ** 2
        alphas_cumprod = alphas_cumprod / alphas_cumprod[0]
        betas = 1 - (alphas_cumprod[1:] / alphas_cumprod[:-1])
        return torch.clip(betas, beta_start, beta_end)
    
    def q_sample(self, x_start, t, noise=None):
        """Forward diffusion process"""
        if noise is None:
            noise = torch.randn_like(x_start)
        
        sqrt_alphas_cumprod_t = self.sqrt_alphas_cumprod.gather(-1, t).view(-1, 1, 1)
        sqrt_one_minus_alphas_cumprod_t = self.sqrt_one_minus_alphas_cumprod.gather(-1, t).view(-1, 1, 1)
        
        return sqrt_alphas_cumprod_t * x_start + sqrt_one_minus_alphas_cumprod_t * noise
    
    def p_losses(self, x_start, t, noise=None):
        """Compute training loss"""
        if noise is None:
            noise = torch.randn_like(x_start)
        
        x_noisy = self.q_sample(x_start=x_start, t=t, noise=noise)
        predicted_noise = self.model(x_noisy, t)
        
        if self.loss_type == 'l2':
            loss = nn.functional.mse_loss(predicted_noise, noise)
        elif self.loss_type == 'l1':
            loss = nn.functional.l1_loss(predicted_noise, noise)
        else:
            raise NotImplementedError()
        
        return loss
    
    @torch.no_grad()
    def p_sample(self, x, t, t_index):
        """Reverse diffusion process - single step"""
        betas_t = self.betas.gather(-1, t).view(-1, 1, 1)
        sqrt_one_minus_alphas_cumprod_t = self.sqrt_one_minus_alphas_cumprod.gather(-1, t).view(-1, 1, 1)
        sqrt_recip_alphas_t = self.sqrt_recip_alphas.gather(-1, t).view(-1, 1, 1)
        
        # Predict noise
        model_output = self.model(x, t)
        
        # Compute mean
        model_mean = sqrt_recip_alphas_t * (
            x - betas_t * model_output / sqrt_one_minus_alphas_cumprod_t
        )
        
        if t_index == 0:
            return model_mean
        else:
            posterior_variance_t = self.posterior_variance.gather(-1, t).view(-1, 1, 1)
            noise = torch.randn_like(x)
            return model_mean + torch.sqrt(posterior_variance_t) * noise
    
    @torch.no_grad()
    def sample(self, shape, return_intermediates=False):
        """Generate samples from noise"""
        device = self.device
        batch_size = shape[0]
        
        # Start from pure noise
        x = torch.randn(shape, device=device)
        
        intermediates = [x]
        
        for i in tqdm(reversed(range(0, self.num_timesteps)), desc='Sampling', total=self.num_timesteps):
            t = torch.full((batch_size,), i, device=device, dtype=torch.long)
            x = self.p_sample(x, t, i)
            
            if return_intermediates and i % 100 == 0:
                intermediates.append(x)
        
        if return_intermediates:
            return x, intermediates
        
        return x

    @torch.no_grad()
    def sample_tied(self, x_start, t_star):
        """
        Row-tied ("SDEdit"-style) sampling used for knockoff generation.

        Forward-noise the OBSERVED rows to diffusion level t_star via q(x_t | x_0),
        then run the learned reverse chain back down to 0.  Row i of the output
        therefore stays statistically tied to row i of x_start, which is what makes
        Cov(X, X_tilde) non-zero.  Uses the SAME trained denoiser -- no retraining.

        t_star == num_timesteps reduces (up to the initial draw) to sample().

        x_start : (n, 1, p) float tensor on self.device
        t_star  : int in [1, num_timesteps]
        """
        device = self.device
        batch_size = x_start.shape[0]
        t_star = int(max(1, min(int(t_star), self.num_timesteps)))

        # --- forward: q(x_{t*} | x_0) starting from the OBSERVED data ---
        t_fwd = torch.full((batch_size,), t_star - 1, device=device, dtype=torch.long)
        x = self.q_sample(x_start=x_start, t=t_fwd)

        # --- reverse: denoise from t* back down to 0 ---
        for i in tqdm(reversed(range(0, t_star)),
                      desc=f'Sampling(tied,t*={t_star})', total=t_star):
            t = torch.full((batch_size,), i, device=device, dtype=torch.long)
            x = self.p_sample(x, t, i)

        return x

class DiffusionXKnockoff:
    """
    End-to-end pipeline:
      Diffusion knockoffs -> train DeepLINK -> compute W (gradient/filter) -> knockoff+ selection

    Inputs match other pipelines:
      X_processed
      y: np.ndarray (n,)
    """
    def __init__(self, input_dim, device=None):
        self.input_dim = input_dim
        self.device = device if device is not None else ('cuda' if torch.cuda.is_available() else 'cpu')

        # Core diffusion object (generator + stats + selection utilities)
        self.diff = DiffKnock(input_dim=input_dim, device=self.device)

        # DeepLINK model (black box)
        self.deepLINK = None

    def run(
        self,
        X_processed, y,
        fdr_threshold=0.2,

        # diffusion training
        diffusion_epochs=300,
        diffusion_batch_size=64,
        diffusion_lr=1e-4,

        # DeepLINK training
        hidden_dims=[50, 20],
        dropout=0.1,
        deeplink_epochs=300,
        deeplink_batch_size=64,
        deeplink_lr=1e-3,
        deeplink_weight_decay=1e-4,

        # which stats
        use_gradient=True,
        use_filter=True
    ):
        


        # --- train diffusion + generate knockoffs ---
        self.diff.train_diffusion_for_knockoffs(
            X_processed,
            n_epochs=diffusion_epochs,
            batch_size=diffusion_batch_size,
            lr=diffusion_lr
        )
        X_knock = self.diff.generate_knockoffs(X_processed, t_star=t_star)

        # --- train DeepLINK once ---
        self.deepLINK = DeepLINK(input_dim=self.input_dim, hidden_dims=hidden_dims, dropout=dropout).to(self.device)

        dataset = TensorDataset(
            torch.FloatTensor(X_processed),
            torch.FloatTensor(X_knock),
            torch.FloatTensor(y)
        )
        dataloader = DataLoader(dataset, batch_size=deeplink_batch_size, shuffle=True)

        criterion = nn.MSELoss()
        optimizer = optim.Adam(self.deepLINK.parameters(), lr=deeplink_lr, weight_decay=deeplink_weight_decay)

        self.deepLINK.train()
        for epoch in range(deeplink_epochs):
            for Xb, Xkb, yb in dataloader:
                Xb = Xb.to(self.device)
                Xkb = Xkb.to(self.device)
                yb = yb.to(self.device)

                optimizer.zero_grad()
                out = self.deepLINK(Xb, Xkb)
                loss = criterion(out.squeeze(), yb)
                loss.backward()
                optimizer.step()

        self.deepLINK.eval()

        # --- compute statistics + select ---
        out = {
            "X_processed": X_processed,
            "X_knockoffs": X_knock,
            "W": {},
            "selected": {}
        }

        if use_gradient:
            W_grad = self.diff.compute_gradient_based_statistics(X_processed, X_knock, y, self.deepLINK, criterion)
            out["W"]["gradient"] = W_grad
            out["selected"]["gradient"] = self.diff.select_features(W_grad, fdr_threshold=fdr_threshold)

        if use_filter:
            W_filt = self.diff.compute_deeplink_statistics(self.deepLINK)
            out["W"]["filter"] = W_filt
            out["selected"]["filter"] = self.diff.select_features(W_filt, fdr_threshold=fdr_threshold)

        return out

# ============= Autoencoder Knockoff =============
